version: "3"

services:
  app:
    build:
      context: .
      dockerfile: "./build/Dockerfile"
    container_name: app
    depends_on:
      - mongodb
      - elastic
    ports:
      - "90:90"
    volumes:
      - ./logs:/logs
    env_file:
      - .env

  telegraf:
    image: telegraf:1.23.0
    container_name: telegraf
    hostname: telegraf
    ports:
      - "9273:9273/tcp"
      - "8125:8125/udp"
    volumes:
      - ./build/config/telegraf/:/etc/telegraf/
    restart: always

  grafana:
    image: grafana/grafana:7.4.3
    container_name: grafana
    depends_on:
      - influxdb
    ports:
      - "3000:3000"
    volumes:
      - grafana:/var/lib/grafana
      - ./build/config/grafana/provisioning:/etc/grafana/provisioning
    restart: always
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false

  influxdb:
    image: influxdb:1.8-alpine
    container_name: influxdb
    restart: always
    environment:
      - INFLUXDB_DB=influx
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
    ports:
      - "8086:8086"
    volumes:
      - influxdb:/var/lib/influxdb

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.3
    container_name: elastic
    restart: always
    ports:
      - "9200:9200"
    volumes:
      - elastic:/usr/share/elasticsearch/data
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms768m -Xmx1024m"
      - "xpack.security.enabled=false"
      - "xpack.security.autoconfiguration.enabled=false"
      - "xpack.security.http.ssl.enabled=false"
      - "xpack.security.transport.ssl.enabled=false"
      - "ingest.geoip.downloader.enabled=false"

  mongodb:
    image: mongo:4.4.6
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - mongodb:/data/db

volumes:
  grafana:
    driver: local
  influxdb:
    driver: local
  elastic:
    driver: local
  mongodb:
    driver: local
