name: Deploy tag to prod
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag for deploy. E.g: v1.0.0'
        required: true

jobs:
  deploy:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Deploy process
        run: |
          echo "Tag was deployed"
