name: "Build"

on: [push]

jobs:
  main:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
      - name: Lint Go
        uses: golangci/golangci-lint-action@v3
      - name: Set up TAG env variable
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        run: |
          if [[ ${GITHUB_REF} == refs/heads/* ]]
          then
            ACTION_REF=${GITHUB_REF:11}
          elif [[ ${GITHUB_REF} == refs/tags/* ]]
          then
            ACTION_REF=${GITHUB_REF:10}
          fi
          
          echo "TAG=" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build image and push it
        uses: docker/build-push-action@v2
        with:
          context: .
          file: build/Dockerfile
          platforms: "linux/amd64,linux/arm64"
          build-args: |
            BUILD_ID=${{ github.sha }}
            VERSION=${{ env.ACTION_REF }}
            GITHUB_TOKEN=${{ secrets.APP_GITHUB_TOKEN }}
          push: false
          tags: |
            ${{ env.TAG }}